In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
# Let's load the dataset
df = pd.read_csv('../data/processed/cleaned_data.csv')
df.shape

(4814, 2)

In [3]:
# Since, we need to split the data, we need a X and y. So, let's go ahead and define them
X = df['text']
y = df['sentiment']
# Splitting the dataset
X_dev, X_test, y_dev, y_test = train_test_split(X,y,test_size=0.15, random_state=42, stratify=y)

In [7]:
# Convert this Series into Dataframe
dev_data = X_dev.to_frame(name='text')
dev_data['sentiment'] = y_dev
dev_data = dev_data.reset_index().rename(columns={'index': 'original_index'})
dev_data

,original_index,text,sentiment
0,418,"Biohit , Inc. , has expanded its mLINE Family ...",neutral
1,347,Net sales went up by 1 % year-on-year to EUR 2...,positive
2,4598,The company confirmed its estimate for lower r...,negative
3,4200,Residents access to the block is planned to be...,neutral
4,2429,Earnings per share were EUR -0.04 -0.06 .,neutral
...,...,...,...
4086,2119,in Q1 2010 18 May 2010 - Finnish electrical co...,positive
4087,611,"OUTOTEC OYJ PRESS RELEASE DECEMBER 4 , 2009 10...",positive
4088,4165,Fortum is looking to invest in several new pro...,neutral
4089,4644,Finnish business software group AffectoGenimap...,negative
4090,1843,It combines a perfect price performance with s...,positive

In [8]:
test_data = X_test.to_frame(name='text')
test_data['sentiment'] = y_test
test_data  = test_data.reset_index().rename(columns={'index':'original_index'})
test_data

,original_index,text,sentiment
0,2636,"The mill will have capacity to produce 500,000...",neutral
1,547,HELSINKI ( AFX ) - Nokian Tyres reported a fou...,positive
2,4685,The company confirmed its estimate for lower r...,negative
3,3071,"Prior to the transaction , whose financial ter...",neutral
4,2988,L+Ænnen Tehtaat 's Food Division was reorganis...,neutral
...,...,...,...
718,4472,"The previously concluded adaptation measures ,...",positive
719,4807,Operating result for the 12-month period decre...,negative
720,3528,Combined net sales in 2006 were $ 27 million a...,neutral
721,4553,Operating profit for the six-month period decr...,neutral
722,226,"( ADP News ) - Feb 11 , 2009 - Finnish managem...",positive

In [10]:
print("Original distribution:")
print(y.value_counts(normalize=True))

print("\nDevelopment distribution:")
print(y_dev.value_counts(normalize=True))

print("\nTest distribution:")
print(y_test.value_counts(normalize=True))

print("\nDev rows:", len(dev_data))
print("Test rows:", len(test_data))
print("Total:", len(dev_data) + len(test_data))
print("Original:", len(df))

Original distribution:
sentiment
neutral     0.591608
positive    0.282925
negative    0.125467
Name: proportion, dtype: float64

Development distribution:
sentiment
neutral     0.591542
positive    0.283060
negative    0.125397
Name: proportion, dtype: float64

Test distribution:
sentiment
neutral     0.591978
positive    0.282158
negative    0.125864
Name: proportion, dtype: float64

Dev rows: 4091
Test rows: 723
Total: 4814
Original: 4814

In [11]:
dev_data.to_csv('../data/processed/dev_data.csv',index=False)
test_data.to_csv('../data/processed/test_data.csv',index=False)